version: 2.0
jobs:
  build:

    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/eatsy

    general:
      branches:
        only: # list of branches to build
          - develop

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}

      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}


        - run:
            name: Run tests
            env:
              COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
            #Give gradlew execution permissions (chmod=+x) via git for this to work
            command: ./gradlew coveralls